// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CramersV_C
double CramersV_C(IntegerVector x, IntegerVector y);
RcppExport SEXP DataMan_CramersV_C(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    __result = Rcpp::wrap(CramersV_C(x, y));
    return __result;
END_RCPP
}
// CramersV_DF
Rcpp::NumericMatrix CramersV_DF(Rcpp::IntegerMatrix dm);
RcppExport SEXP DataMan_CramersV_DF(SEXP dmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dm(dmSEXP);
    __result = Rcpp::wrap(CramersV_DF(dm));
    return __result;
END_RCPP
}
