# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CramersV_C <- function(x, y) {
    .Call('_DataMan_CramersV_C', PACKAGE = 'DataMan', x, y)
}

CramersV_DF <- function(dm) {
    .Call('_DataMan_CramersV_DF', PACKAGE = 'DataMan', dm)
}

